### PR TITLE
Fix CI build and test failures

### LINKED ISSUE #74: Make CI pass
The CI is fails for the repo. We need to make the CI pass and make sure all tests are passed.

For starters:

- Check `SonarQube Analysis` is working correctly or not
- Run the package and single and parallel tests

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
Fix CI issues causing build failures in GitHub Actions

## Changes
- Regenerate package-lock.json to resolve npm install integrity checksum failures
- Add missing `chai` dependency for Mocha tests
- Fix Gulpfile to run Mocha only on `test/mocha/**/*.js` files (not TestCafe tests)
- Update browser test to use generic assertions instead of outdated browser versions

## Testing
- Build passes with linting
- Unit tests pass
- TestCafe integration works (check with accesskey and username env creation and integration)

Fixes #74

### CODE REVIEW

**Comment by ARYPROGRAMMER** [comment]
for review: @Delta456 

please go ahead i think this would work now

**Comment by ARYPROGRAMMER** [comment]
can someone check this pls

@Delta456 or @tiago154 and other maintainers

File: test/mocha/browser-names-test.js [hunk 1]
```diff
@@ -13,28 +13,13 @@ describe('Browser names', function () {
...
-                'Chrome@76.0:OS X El Capitan',
-                'Chrome@75.0:OS X El Capitan',
-                'Firefox@67.0:OS X El Capitan',
-                'Firefox@66.0:OS X El Capitan',
-                'Chrome@74.0:OS X Yosemite',
-                'Chrome@73.0:OS X Yosemite',
-                'Firefox@66.0:OS X Yosemite',
-                'Firefox@65.0:OS X Yosemite',
-                'Chrome@67.0:OS X Mavericks',
-                'Chrome@66.0:OS X Mavericks',
```
Comment (Delta456) [inline test/mocha/browser-names-test.js:28]: Please don't remove this. These are essential for testing.

File: package-lock.json
Comment (Delta456) [inline package-lock.json:1]: Undo the changes made here.

File: test/mocha/browser-names-test.js (hunk 1 above)
Comment (ARYPROGRAMMER) [reply test/mocha/browser-names-test.js:28]: ok surely i thought migrating would be good

File: package-lock.json
Comment (ARYPROGRAMMER) [reply package-lock.json:1]: i thought the lock was old, reverting

**Comment by ARYPROGRAMMER** [comment]
@Delta456 done with the changes

**Comment by Delta456** [comment]
> @Delta456 done with the changes

Great, can you also add screenshot for asserting the test is now passing? I also see the CI not being built 🤔

**Comment by ARYPROGRAMMER** [comment]
> Please don't remove this. These are essential for testing.

the browser list is outdated, the api returns:

```bash
 Browser names
[
  'Chrome@143.0:Windows 11',
  'Chrome@142.0:Windows 11',
  'Chrome@141.0:Windows 11',
  'Chrome@140.0:Windows 11',
  'Chrome@139.0:Windows 11',
  'Chrome@138.0:Windows 11',
  'Chrome@137.0:Windows 11',
  'Chrome@136.0:Windows 11',
  'Chrome@135.0:Windows 11',
  'Chrome@134.0:Windows 11',
  'Chrome@133.0:Windows 11',
  'Chrome@132.0:Windows 11',
  'Chrome@131.0:Windows 11',
  'Chrome@130.0:Windows 11',
  'Chrome@129.0:Windows 11',
  'Chrome@128.0:Windows 11',
  'Chrome@127.0:Windows 11',
  'Chrome@126.0:Windows 11',
  'Chrome@125.0:Windows 11',
  'Chrome@124.0:Windows 11',
  'Chrome@123.0:Windows 11',
  'Chrome@122.0:Windows 11',
  'Chrome@121.0:Windows 11',
  'Chrome@120.0:Windows 11',
  'Chrome@119.0:Windows 11',
  'Chrome@118.0:Windows 11',
  'Chrome@117.0:Windows 11',
  'Chrome@116.0:Windows 11',
  'Chrome@115.0:Windows 11',
  'Chrome@114.0:Windows 11',
  'Chrome@113.0:Windows 11',
  'Chrome@112.0:Windows 11',
  'Chrome@111.0:Windows 11',
  'Chrome@110.0:Windows 11',
  'Chrome@109.0:Windows 11',
  'Chrome@108.0:Windows 11',
  'Chrome@107.0:Windows 11',
  'Chrome@106.0:Windows 11',
  'Chrome@105.0:Windows 11',
  'Chrome@104.0:Windows 11',
  'Chrome@103.0:Windows 11',
  'Chrome@102.0:Windows 11',
  'Chrome@101.0:Windows 11',
  'Chrome@100.0:Windows 11',
  'Chrome@99.0:Windows 11',
  'Chrome@98.0:Windows 11',
  'Chrome@97.0:Windows 11',
  'Chrome@96.0:Windows 11',
  'Chrome@95.0:Windows 11',
  'Chrome@94.0:Windows 11',
  'Chrome@93.0:Windows 11',
  'Chrome@92.0:Windows 11',
  'Chrome@91.0:Windows 11',
  'Chrome@90.0:Windows 11',
  'Chrome@89.0:Windows 11',
  'Chrome@88.0:Windows 11',
  'Chrome@87.0:Windows 11',
  'Chrome@86.0:Windows 11',
  'Chrome@85.0:Windows 11',
  'Chrome@84.0:Windows 11',
  'Chrome@83.0:Windows 11',
  'Chrome@81.0:Windows 11',
  'Chrome@80.0:Windows 11',
  'Chrome@79.0:Windows 11',
  'Chrome@78.0:Windows 11',
  'Chrome@77.0:Windows 11',
  'Chrome@76.0:Windows 11',
  'Chrome@75.0:Windows 11',
  'Chrome@74.0:Windows 11',
  'Chrome@73.0:Windows 11',
  'Chrome@72.0:Windows 11',
  'Chrome@71.0:Windows 11',
  'Chrome@70.0:Windows 11',
  'Chrome@69.0:Windows 11',
  'Chrome@68.0:Windows 11',
  'Chrome@67.0:Windows 11',
  'Chrome@66.0:Windows 11',
  'Chrome@65.0:Windows 11',
  'Chrome@64.0:Windows 11',
  'Chrome@63.0:Windows 11',
  'Chrome@62.0:Windows 11',
  'Chrome@61.0:Windows 11',
  'Chrome@60.0:Windows 11',
  'Chrome@59.0:Windows 11',
  'Chrome@58.0:Windows 11',
  'Chrome@57.0:Windows 11',
  'Chrome@56.0:Windows 11',
  'Chrome@55.0:Windows 11',
  'Chrome@54.0:Windows 11',
  'Chrome@53.0:Windows 11',
  'Chrome@52.0:Windows 11',
  'Chrome@51.0:Windows 11',
  'Chrome@50.0:Windows 11',
  'Chrome@49.0:Windows 11',
  'Chrome@48.0:Windows 11',
  'Chrome@47.0:Windows 11',
  'Chrome@46.0:Windows 11',
  'ChromeFT@143.0:Windows 11',
  'ChromeFT@142.0:Windows 11',
  'ChromeFT@141.0:Windows 11',
  ... 4433 more items
]
[
  true,  true,  false,
  false, false, false,
  false, false, false,
  false, false, false
]
    √ Should return list of common browsers and devices

.....
```

and since we are testing against

```bash
 const commonBrowsers = [
                'Internet Explorer@11.0:Windows 7',
                'Internet Explorer@10.0:Windows 7',
                'Chrome@76.0:OS X El Capitan',
                'Chrome@75.0:OS X El Capitan',
                'Firefox@67.0:OS X El Capitan',
                'Firefox@66.0:OS X El Capitan',
                'Chrome@74.0:OS X Yosemite',
                'Chrome@73.0:OS X Yosemite',
                'Firefox@66.0:OS X Yosemite',
                'Firefox@65.0:OS X Yosemite',
                'Chrome@67.0:OS X Mavericks',
                'Chrome@66.0:OS X Mavericks',
            ];
```

its failing.

either we can use, removing exact array and just confirming the length
```
expect(list.length).to.be.greaterThan(10);
```

or i can update the browsers to latest -> let me know if i should commit this , previous browser list is failing

here's the o.p:

image

for the ci, it might be creds issue or branch filter issue - currently not focusing on that

cc: @Delta456

**Comment by ARYPROGRAMMER** [comment]
let me know if i should commit this, rest everything would work, it obviously requires $env:LT_USERNAME = ; $env:LT_ACCESS_KEY =

@Delta456

**Comment by Delta456** [comment]
> or i can update the browsers to latest -> let me know if i should commit this , previous browser list is failing

Update the browsers list to latest

> obviously requires $env:LT_USERNAME = ; $env:LT_ACCESS_KEY =

I will get back to you on this.

**Comment by ARYPROGRAMMER** [comment]
did that, here's how i run and the output

image

i'll obviously delete the keys after the pr is merged

cc: @Delta456

**Comment by Delta456** [comment]
Can you also run `testcafe "lambdatest:Chrome@141.0:Windows 11" "test/test.js"`? We also need to update the CI file https://github.com/LambdaTest/testcafe-browser-provider-lambdatest/blob/master/.github/workflows/main.yml

**Comment by ARYPROGRAMMER** [comment]
image

@Delta456 

note: this required downgrading pify for me: 
image

also suggested change for main.yml:

image

Moreover i think it is working currently and rest of the parts can be later integrated

**Comment by ARYPROGRAMMER** [comment]
adding the package change and package lock regeneration is best addition this pr can do currently , rest is addressed. ci auto run and update of packages is seen as new issue itself

cc: @Delta456

**Comment by Delta456** [comment]
You mean to address the CI changes in another PR? It works with me

**Comment by ARYPROGRAMMER** [comment]
> You mean to address the CI changes in another PR? It works with me

Yes if any lets dissect it somewhere else (most likely version and branch filter issue) 

For specific build and test fixtures this pr works

**Comment by ARYPROGRAMMER** [comment]
let me know more on this @Delta456

**Review by Delta456 — APPROVED** [review]
